# Generated by Django 3.0.8 on 2021-03-04 14:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ImageField(blank=True, upload_to='portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(default='DEFAULT VALUE'),
        ),
        migrations.DeleteModel(
            name='UserBlog',
        ),
    ]
