# Generated by Django 3.0.8 on 2020-08-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_userblog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_on',
            field=models.DateTimeField(null=True),
        ),
    ]
