# Generated by Django 3.0.8 on 2020-10-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20201027_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptions', models.CharField(max_length=300)),
                ('image', models.ImageField(default='portfolio/images/logo.png', upload_to='portfolio/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Project',
            new_name='ML_Project',
        ),
    ]
